name: Feature Request
description: Suggest a new feature or enhancement for Hogsync
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-flight checklist
      description: Please check the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I have read the [documentation](https://github.com/your-username/hogsync#readme)
          required: true
        - label: This feature request is not covered by existing functionality
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the motivation?
      placeholder: |
        I'm always frustrated when...
        This would help with...
        Currently it's difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to see...
        The feature should work by...
        Users would be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        Alternative 1: ...
        Alternative 2: ...
        I considered using X but...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my adoption
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low - Small change or addition
        - Medium - Moderate development effort
        - High - Significant development effort
        - Unknown - Not sure

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        In my project, I need to...
        This would allow me to...
        My team would benefit because...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would be used (code snippets, CLI commands, etc.)
      placeholder: |
        // Example usage:
        hogsync new-command --option value

        // Or in code:
        const result = newFeature();
      render: javascript

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature works with Next.js
        - [ ] Feature works with Vite
        - [ ] Documentation is updated
        - [ ] Tests are included

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this feature require breaking changes to existing APIs?
      options:
        - No - Fully backward compatible
        - Maybe - Might require minor changes
        - Yes - Would require breaking changes
        - Unknown - Not sure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
        - label: I would be willing to help with testing this feature
        - label: I would be willing to help with documentation for this feature

